### ISSUE TITLE
Please document availability against PG versions

### ISSUE THREAD

**Issue by vpicavet** [erthalion/jsonbx#4]
Hi,

It would be nice to add information in the README about availability of these functions in the various PostgreSQL versions. Some are already present in stock PG 9.5 I think.

**Comment by babsonmatt** [comment]
looks like jsonb_set and jsonb_pretty are in 9.5 alpha1

**Comment by erthalion** [comment]
Hi, @vpicavet 

Yes, I'll add this information soon (and it'll we especially useful due to furher development, because part functionality will be available only for 9.5 or 9.4). Generally speaking, all implemented functions are in 9.5 now (see this [commit](http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=c6947010ceb42143d9f047c65c1eac2b38928ab7), and don't be confused by the `jsonb_replace -> jsonb_set` transformation).

**Comment by erthalion** [comment]
Well, I mentioned all required information about availability in the readme, so I think we can close this issue. I'll keep this info updated.
